import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { Search, Zap, Shield, BarChart2, ArrowRight } from 'lucide-react'
import { fetchStats } from '../utils/api'

export default function HomePage() {
  const navigate = useNavigate()
  const [searchVal, setSearchVal] = useState('')

  const { data: stats } = useQuery({
    queryKey: ['stats'],
    queryFn: fetchStats,
    retry: false,
  })

  const handleSearch = (e) => {
    e.preventDefault()
    navigate(`/browse?q=${encodeURIComponent(searchVal)}`)
  }

  const features = [
    {
      icon: <Search size={20} />,
      title: 'Semantic Search',
      desc: 'Ask questions in plain English. ChromaDB finds the most relevant reviews and specs instantly.',
    },
    {
      icon: <Zap size={20} />,
      title: 'Local LLM (Ollama)',
      desc: 'Answers generated by Llama 3 running on your machine. No API keys. Full privacy.',
    },
    {
      icon: <Shield size={20} />,
      title: 'Explainable AI',
      desc: 'Every answer comes with source evidence, confidence scores, and sentiment breakdowns.',
    },
    {
      icon: <BarChart2 size={20} />,
      title: 'Aspect Analysis',
      desc: 'Understand what customers say about battery, comfort, price, sound — broken down by aspect.',
    },
  ]

  return (
    <div className="animate-fade-in">
      {/* Hero */}
      <section className="relative overflow-hidden bg-ink text-paper">
        {/* Decorative grid */}
        <div
          className="absolute inset-0 opacity-5"
          style={{
            backgroundImage: 'linear-gradient(#fff 1px, transparent 1px), linear-gradient(90deg, #fff 1px, transparent 1px)',
            backgroundSize: '48px 48px',
          }}
        />
        <div className="relative max-w-4xl mx-auto px-6 py-24 text-center">
          <p className="section-label text-slate-400 mb-5">Master's Project · UMass Dartmouth · MS Data Science</p>
          <h1 className="font-display text-5xl md:text-6xl font-semibold leading-tight mb-6">
            Explainable AI for <br />
            <em className="text-amber not-italic">Product Intelligence</em>
          </h1>
          <p className="font-sans text-slate-300 text-lg max-w-2xl mx-auto mb-10 leading-relaxed">
            Ask natural language questions about any product. Get grounded answers from customer
            reviews and metadata — with full transparency into why.
          </p>

          {/* Search bar */}
          <form onSubmit={handleSearch} className="flex max-w-xl mx-auto gap-0 mb-4">
            <input
              value={searchVal}
              onChange={e => setSearchVal(e.target.value)}
              placeholder='Search products, e.g. "wireless headphones"…'
              className="input-base bg-white/10 border-white/20 text-paper placeholder:text-slate-400 flex-1"
            />
            <button type="submit" className="btn-primary whitespace-nowrap flex items-center gap-2">
              <Search size={15} /> Search
            </button>
          </form>

          <button
            onClick={() => navigate('/browse')}
            className="text-sm text-slate-400 hover:text-amber transition-colors duration-150 flex items-center gap-1 mx-auto"
          >
            Browse all products <ArrowRight size={13} />
          </button>
        </div>
      </section>

      {/* Stats bar */}
      {stats && (
        <section className="border-b border-slate-200 bg-paper">
          <div className="max-w-4xl mx-auto px-6 py-5 flex flex-wrap justify-center gap-10">
            {[
              ['Products indexed', stats.total_products],
              ['Review chunks', stats.total_review_chunks],
              ['Vector DB', stats.vector_db],
              ['Embedding model', stats.embedding_model],
            ].map(([label, val]) => (
              <div key={label} className="text-center">
                <div className="font-mono text-lg font-medium text-ink">{val}</div>
                <div className="section-label text-slate-400 mt-0.5">{label}</div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Features grid */}
      <section className="max-w-5xl mx-auto px-6 py-20">
        <p className="section-label text-center mb-3">How it works</p>
        <h2 className="font-display text-3xl text-center text-ink mb-12">
          From question to explainable answer
        </h2>
        <div className="grid md:grid-cols-2 gap-px bg-slate-200">
          {features.map(({ icon, title, desc }) => (
            <div key={title} className="bg-cream p-8 flex gap-5">
              <div className="w-10 h-10 bg-ink text-paper flex items-center justify-center shrink-0">
                {icon}
              </div>
              <div>
                <h3 className="font-display text-lg font-semibold mb-2">{title}</h3>
                <p className="text-sm text-slate-600 leading-relaxed font-sans">{desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Architecture diagram */}
      <section className="bg-ink text-paper py-16 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <p className="section-label text-slate-500 mb-3">System Architecture</p>
          <h2 className="font-display text-3xl mb-10">End-to-end RAG pipeline</h2>
          <div className="flex flex-wrap justify-center items-center gap-3 font-mono text-sm">
            {[
              'Amazon Reviews',
              '→',
              'NLP Preprocessing',
              '→',
              'ChromaDB Embeddings',
              '→',
              'Semantic Retrieval',
              '→',
              'Ollama Llama 3',
              '→',
              'Explainability Layer',
              '→',
              'React UI',
            ].map((step, i) => (
              step === '→'
                ? <span key={i} className="text-slate-500 text-lg">→</span>
                : (
                  <span key={i} className="bg-white/10 border border-white/10 px-3 py-1.5 text-xs">
                    {step}
                  </span>
                )
            ))}
          </div>
        </div>
      </section>
    </div>
  )
}
