import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { Search, Zap, Shield, BarChart2, ArrowRight } from 'lucide-react'
import { fetchStats, fetchProducts } from '../utils/api'
import { useAuth } from '../context/AuthContext'

export default function HomePage() {
  const navigate = useNavigate()
  const [searchVal, setSearchVal] = useState('')
  const { user, getAnalyticsSummary, trackActivity } = useAuth()
  const analyticsSummary = getAnalyticsSummary()

  const { data: stats } = useQuery({
    queryKey: ['stats'],
    queryFn: fetchStats,
    retry: false,
  })

  const { data: recommendationData } = useQuery({
    queryKey: ['recommendation-products'],
    queryFn: () => fetchProducts({ limit: 120 }),
    staleTime: 60_000,
  })

  const recommendedProducts = (() => {
    const products = recommendationData?.products || []
    if (!products.length) return []

    const preferredCategory = analyticsSummary?.preferences?.category
    const preferredBrand = analyticsSummary?.preferences?.brand
    const preferredRange = analyticsSummary?.preferences?.priceRange

    const getRangeScore = (price) => {
      if (!preferredRange || preferredRange === 'all') return 0
      if (preferredRange === '1000+') return price >= 1000 ? 1 : 0
      const [min, max] = preferredRange.split('-').map(Number)
      if (!Number.isFinite(min) || !Number.isFinite(max)) return 0
      return price >= min && price <= max ? 1 : 0
    }

    const ranked = [...products].sort((a, b) => {
      const scoreA =
        (preferredCategory && a.category === preferredCategory ? 2 : 0) +
        (preferredBrand && a.brand === preferredBrand ? 2 : 0) +
        getRangeScore(Number(a.price))
      const scoreB =
        (preferredCategory && b.category === preferredCategory ? 2 : 0) +
        (preferredBrand && b.brand === preferredBrand ? 2 : 0) +
        getRangeScore(Number(b.price))
      return scoreB - scoreA
    })

    return ranked.slice(0, 6)
  })()

  const handleSearch = (e) => {
    e.preventDefault()
    navigate(`/browse?q=${encodeURIComponent(searchVal)}`)
  }

  const features = [
    {
      icon: <Search size={20} />,
      title: 'Semantic Search',
      desc: 'Ask questions in plain English. ChromaDB finds the most relevant reviews and specs instantly.',
    },
    {
      icon: <Zap size={20} />,
      title: 'Local LLM (Ollama)',
      desc: 'Answers generated by Llama 3 running on your machine. No API keys. Full privacy.',
    },
    {
      icon: <Shield size={20} />,
      title: 'Explainable AI',
      desc: 'Every answer comes with source evidence, confidence scores, and sentiment breakdowns.',
    },
    {
      icon: <BarChart2 size={20} />,
      title: 'Aspect Analysis',
      desc: 'Understand what customers say about battery, comfort, price, sound — broken down by aspect.',
    },
  ]

  return (
    <div className="animate-fade-in">
      {/* Hero */}
      <section className="relative overflow-hidden bg-ink text-paper">
        {/* Decorative grid */}
        <div
          className="absolute inset-0 opacity-5"
          style={{
            backgroundImage: 'linear-gradient(#fff 1px, transparent 1px), linear-gradient(90deg, #fff 1px, transparent 1px)',
            backgroundSize: '48px 48px',
          }}
        />
        <div className="relative max-w-4xl mx-auto px-6 py-24 text-center">
          <p className="section-label text-slate-400 mb-5">Master's Project · UMass Dartmouth · MS Data Science</p>
          <h1 className="font-display text-5xl md:text-6xl font-semibold leading-tight mb-6">
            Explainable AI for <br />
            <em className="text-amber not-italic">Product Intelligence</em>
          </h1>
          <p className="font-sans text-slate-300 text-lg max-w-2xl mx-auto mb-10 leading-relaxed">
            Ask natural language questions about any product. Get grounded answers from customer
            reviews and metadata — with full transparency into why.
          </p>

          {/* Search bar */}
          <form onSubmit={handleSearch} className="flex max-w-xl mx-auto gap-0 mb-4">
            <input
              value={searchVal}
              onChange={e => setSearchVal(e.target.value)}
              placeholder='Search products, e.g. "wireless headphones"…'
              className="input-base bg-white/10 border-white/20 text-paper placeholder:text-slate-400 flex-1"
            />
            <button type="submit" className="btn-primary whitespace-nowrap flex items-center gap-2">
              <Search size={15} /> Search
            </button>
          </form>

          <button
            onClick={() => navigate('/browse')}
            className="text-sm text-slate-400 hover:text-amber transition-colors duration-150 flex items-center gap-1 mx-auto"
          >
            Browse all products <ArrowRight size={13} />
          </button>
        </div>
      </section>

      {/* Stats bar */}
      {stats && (
        <section className="border-b border-slate-200 bg-paper">
          <div className="max-w-4xl mx-auto px-6 py-5 flex flex-wrap justify-center gap-10">
            {[
              ['Products indexed', stats.total_products],
              ['Review chunks', stats.total_review_chunks],
              ['Vector DB', stats.vector_db],
              ['Embedding model', stats.embedding_model],
            ].map(([label, val]) => (
              <div key={label} className="text-center">
                <div className="font-mono text-lg font-medium text-ink">{val}</div>
                <div className="section-label text-slate-400 mt-0.5">{label}</div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Features grid */}
      <section className="max-w-5xl mx-auto px-6 py-20">
        <p className="section-label text-center mb-3">How it works</p>
        <h2 className="font-display text-3xl text-center text-ink mb-12">
          From question to explainable answer
        </h2>
        <div className="grid md:grid-cols-2 gap-px bg-slate-200">
          {features.map(({ icon, title, desc }) => (
            <div key={title} className="bg-cream p-8 flex gap-5">
              <div className="w-10 h-10 bg-ink text-paper flex items-center justify-center shrink-0">
                {icon}
              </div>
              <div>
                <h3 className="font-display text-lg font-semibold mb-2">{title}</h3>
                <p className="text-sm text-slate-600 leading-relaxed font-sans">{desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Personalized analytics + recommendations */}
      {user && (
        <section className="max-w-6xl mx-auto px-6 pb-16">
          <div className="mb-8">
            <p className="section-label mb-2">Personalized Insights</p>
            <h2 className="font-display text-3xl text-ink">Analytics & Recommendations For You</h2>
            <p className="text-sm text-slate-500 mt-2 font-sans">
              Based on your browsing and AI question activity, here are tailored suggestions.
            </p>
          </div>

          <div className="grid md:grid-cols-4 gap-3 mb-6">
            <div className="card bg-white p-4">
              <p className="section-label">Searches</p>
              <p className="font-display text-2xl text-ink">{analyticsSummary.counts.searches}</p>
            </div>
            <div className="card bg-white p-4">
              <p className="section-label">Product Views</p>
              <p className="font-display text-2xl text-ink">{analyticsSummary.counts.productViews}</p>
            </div>
            <div className="card bg-white p-4">
              <p className="section-label">Questions Asked</p>
              <p className="font-display text-2xl text-ink">{analyticsSummary.counts.questionsAsked}</p>
            </div>
            <div className="card bg-white p-4">
              <p className="section-label">Top Preference</p>
              <p className="font-mono text-sm text-ink mt-1">
                {analyticsSummary.preferences.brand || analyticsSummary.preferences.category || 'No preference yet'}
              </p>
            </div>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {recommendedProducts.map((p) => (
              <article key={p.product_id} className="card bg-white p-4">
                <div className="h-36 overflow-hidden border border-slate-100 mb-3">
                  <img src={p.image_url} alt={p.title} className="w-full h-full object-cover" />
                </div>
                <p className="text-xs font-mono text-slate-400">{p.brand} · {p.category}</p>
                <h3 className="font-display text-base text-ink mt-1 mb-2 leading-snug">{p.title}</h3>
                <div className="flex items-center justify-between">
                  <span className="font-mono font-semibold text-ink">${p.price}</span>
                  <div className="flex gap-2">
                    <button
                      onClick={() => {
                        trackActivity('recommendation_click', { productId: p.product_id, source: 'home' })
                        navigate(`/product/${p.product_id}`)
                      }}
                      className="text-[10px] font-mono px-2 py-1 border border-slate-200 text-slate-600 hover:text-ink"
                    >
                      Ask AI
                    </button>
                    <a
                      href={p.external_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      onClick={() => trackActivity('recommendation_open_product_page', { productId: p.product_id, source: 'home' })}
                      className="text-[10px] font-mono px-2 py-1 border border-ink text-ink hover:bg-ink hover:text-paper"
                    >
                      Open
                    </a>
                  </div>
                </div>
              </article>
            ))}
          </div>
        </section>
      )}

      {/* Architecture diagram */}
      <section className="bg-ink text-paper py-16 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <p className="section-label text-slate-500 mb-3">System Architecture</p>
          <h2 className="font-display text-3xl mb-10">End-to-end RAG pipeline</h2>
          <div className="flex flex-wrap justify-center items-center gap-3 font-mono text-sm">
            {[
              'Amazon Reviews',
              '→',
              'NLP Preprocessing',
              '→',
              'ChromaDB Embeddings',
              '→',
              'Semantic Retrieval',
              '→',
              'Ollama Llama 3',
              '→',
              'Explainability Layer',
              '→',
              'React UI',
            ].map((step, i) => (
              step === '→'
                ? <span key={i} className="text-slate-500 text-lg">→</span>
                : (
                  <span key={i} className="bg-white/10 border border-white/10 px-3 py-1.5 text-xs">
                    {step}
                  </span>
                )
            ))}
          </div>
        </div>
      </section>
    </div>
  )
}
